# disable all the crates by default
[workspace]
publish = false
git_tag_enable = false
git_release_enable = false
semver_check = false
changelog_update = false
# TODO: light-client produces some trash files
allow_dirty = true

# enable celestia-tendermint
[[package]]
name = "celestia-tendermint"
publish = true
git_tag_enable = true
git_release_enable = true
semver_check = true
changelog_update = true

# enable celestia-tendermint-proto
[[package]]
name = "celestia-tendermint-proto"
publish = true
git_tag_enable = true
git_release_enable = true
semver_check = true
changelog_update = true
