name: Rust
on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - 'v*.*.*-celestia'
jobs:
  # cleanup-runs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: rokroskar/workflow-run-cleanup-action@master
  #       env:
  #         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  #   if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run clippy
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run clippy
        run: cargo clippy --all --all-targets

  # clippy-tools-output:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         components: clippy
  #         override: true
  #     - uses: actions-rs/clippy-check@v1
  #       with:
  #         name: clippy-tools-results
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         args: --manifest-path tools/kvstore-test/Cargo.toml --all-features --all-targets -- -Dwarnings -Drust-2018-idioms

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo doc
        run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        # toolchain: nightly-2023-03-01 # regression prevents docs from building
